name: Daily Commit

on:
  schedule:
    - cron: '0 9 * * *'  # daily at 09:00 UTC
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # ensure it uses proper token

      - name: Add commit for 25ds2000002@ds.study.iitm.ac.in
        run: |
          echo "Daily commit $(date)" >> daily.txt
          git config user.name "25ds2000002"
          git config user.email "25ds2000002@ds.study.iitm.ac.in"
          git add daily.txt
          git commit -m "Daily commit by 25ds2000002" || echo "No changes to commit"
          git push
