name: Daily Commit

on:
  schedule:
    # Runs at 12:00 UTC every day
    - cron: '0 12 * * *'

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "25ds2000002"
          git config user.email "25ds2000002@ds.study.iitm.ac.in"

      - name: Add daily commit
        run: |
          echo "Daily commit $(date)" >> daily.txt
          git add daily.txt
          git commit -m "Daily commit by 25ds2000002" || echo "No changes to commit"
          git push
